"""Criando models

Revision ID: cfa05bb32377
Revises: 
Create Date: 2026-03-08 01:19:51.736304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'cfa05bb32377'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('BRL', 'USD', 'EUR', name='currencies', schema='finance'), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_asset_prices_date'), 'asset_prices', ['date'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_asset_prices_symbol'), 'asset_prices', ['symbol'], unique=False, schema='finance')
    op.create_table('exchange_rates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.Enum('BRL', 'USD', 'EUR', name='currencies', schema='finance'), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_exchange_rates_date'), 'exchange_rates', ['date'], unique=False, schema='finance')
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telegram_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('outcome', 'income', name='categorytype', schema='finance'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_categories_user_id'), 'categories', ['user_id'], unique=False, schema='finance')
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['finance.categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_tags_category_id'), 'tags', ['category_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_tags_user_id'), 'tags', ['user_id'], unique=False, schema='finance')
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('date_transaction', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('BRL', 'USD', 'EUR', name='currencies', schema='finance'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('index_rate', sa.Float(), nullable=True),
    sa.Column('index', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['finance.tags.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_transactions_tag_id'), 'transactions', ['tag_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_transactions_user_id'), 'transactions', ['user_id'], unique=False, schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_transactions_user_id'), table_name='transactions', schema='finance')
    op.drop_index(op.f('ix_finance_transactions_tag_id'), table_name='transactions', schema='finance')
    op.drop_table('transactions', schema='finance')
    op.drop_index(op.f('ix_finance_tags_user_id'), table_name='tags', schema='finance')
    op.drop_index(op.f('ix_finance_tags_category_id'), table_name='tags', schema='finance')
    op.drop_table('tags', schema='finance')
    op.drop_index(op.f('ix_finance_categories_user_id'), table_name='categories', schema='finance')
    op.drop_table('categories', schema='finance')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_finance_exchange_rates_date'), table_name='exchange_rates', schema='finance')
    op.drop_table('exchange_rates', schema='finance')
    op.drop_index(op.f('ix_finance_asset_prices_symbol'), table_name='asset_prices', schema='finance')
    op.drop_index(op.f('ix_finance_asset_prices_date'), table_name='asset_prices', schema='finance')
    op.drop_table('asset_prices', schema='finance')
    # ### end Alembic commands ###
